name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: i686-unknown-linux-gnu
          components: rustfmt, clippy, miri
      - name: Test (debug)
        run: cargo test
      - name: Test (release)
        run: cargo test --release
      - name: Install GCC multilib
        run: sudo apt install gcc-multilib
      - name: Test (32-bit)
        run: cargo test --target i686-unknown-linux-gnu
      - name: Install Miri
        run: cargo miri setup
      - name: Test (miri)
        run: MIRIFLAGS="-Zmiri-permissive-provenance" cargo miri test
      - name: Test (miri big-endian)
        run: MIRIFLAGS="-Zmiri-permissive-provenance" cargo miri test --target mips64-unknown-linux-gnuabi6