name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy, miri
      - name: Test (debug)
        run: cargo test
      - name: Test (release)
        run: cargo test --release
      - name: Install Miri
        run: cargo miri setup
      - name: Test (miri)
        run: cargo miri test --tests
      - name: Test (miri big-endian)
        run: cargo miri test --target mips64-unknown-linux-gnuabi6 --tests